//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shubhkarya.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SubhkaryaEntities : DbContext
    {
        public SubhkaryaEntities()
            : base("name=SubhkaryaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblEducation> tblEducations { get; set; }
        public virtual DbSet<tblHeight> tblHeights { get; set; }
        public virtual DbSet<tblIncome> tblIncomes { get; set; }
        public virtual DbSet<tblProfession> tblProfessions { get; set; }
        public virtual DbSet<tblReg> tblRegs { get; set; }
    }
}
